
AsciiComments:
  Enabled: false

MethodLength:
  Max: 30

LineLength:
  Max: 160

AbcSize:
  Max: 40

AllCops:
  RunRailsCops: true
  Exclude:
    - bin/*
    - config/unicorn.rb
    - config/unicorn_staging.rb
    - db/schema.rb
    - db/migrate/*
    - Guardfile
    - Gemfile
    - vendor/bundle/**/*
    - spec/rails_helper.rb
    - spec/spec_helper.rb
    - tmp/**/*
